# Generated by Django 4.2.11 on 2024-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
