# Generated by Django 4.2.11 on 2024-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_report_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedaempresa', models.CharField(max_length=50)),
            ],
        ),
    ]
