# Generated by Django 4.2.11 on 2024-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_nomedaempresa_settingsreport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='endpoint',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
